export interface GuaranteeExample {
  area: string;
  implementation: { path: string; anchor: string };
  oracle: { path: string; anchor: string } | null;
  grade: "source-inspected" | "test-inspected" | "mutation-tested";
  runEvidence: string[];
  limit: string;
}
export interface GuaranteeDefinition {
  id: string;
  title: string;
  category: string;
  promise: string;
  appliesWhen: string;
  parameters: string[];
  excludes: string;
  falsifier: string;
  demoteWhen: string;
  distinctFrom: { id: string; because: string };
  example: GuaranteeExample;
}

const inspected = (area: string, path: string, anchor: string, testPath: string | null, testAnchor: string, limit: string): GuaranteeExample => ({
  area, implementation: { path, anchor }, oracle: testPath ? { path: testPath, anchor: testAnchor } : null,
  grade: testPath ? "test-inspected" : "source-inspected", runEvidence: [], limit,
});
const controlled = (example: GuaranteeExample, ...runEvidence: string[]): GuaranteeExample => ({ ...example, grade: "mutation-tested", runEvidence });
const other = (id: string, because: string) => ({ id: `guarantee:${id}`, because });
const grpc = "nodejs/src/ingestion/api/grpc-server.ts";
const grpcTest = "nodejs/src/ingestion/api/grpc-server.test.ts";
const cacheTest = "posthog/query_cache/test/test_storage.py";
const cacheScript = "posthog/query_cache/size_tracker.py";
const dedup = "nodejs/src/ingestion/common/feature-flag-called-dedup/feature-flag-called-dedup-service.ts";
const dedupTest = "nodejs/src/ingestion/common/feature-flag-called-dedup/feature-flag-called-dedup-service.test.ts";
const encryption = "posthog/helpers/encrypted_fields.py";
const encryptionTest = "posthog/helpers/tests/test_encrypted_fields.py";
const vm = "common/hogvm/typescript/src/execute.ts";
const vmTest = "common/hogvm/typescript/src/__tests__/execute.test.ts";
const r2 = "docs/assays/posthog-guarantees-r2/";
const r3 = "docs/assays/posthog-guarantees-r3/";

/** Candidate reference vocabulary. It does not participate in taxonomy activation or verdict derivation. */
export const GUARANTEE_CATALOG: {
  version: string; maturity: "candidate"; applicability: "caller-assessed"; portability: "unproven";
  source: { repository: string; commit: string }; limit: string; definitions: GuaranteeDefinition[];
} = {
  version: "coherence-guarantees/v0", maturity: "candidate", applicability: "caller-assessed", portability: "unproven",
  source: { repository: "https://github.com/PostHog/posthog", commit: "c54fec2163ad9455fd23a947f86a9034c1df9388" },
  limit: "Candidate vocabulary, not activated obligations or satisfaction. PostHog examples are author-selected, scoped and unevenly tested. No whole-project coverage, portable activation or immutable receipt is established. Historical taxonomy suggestions and spec claims retain their existing identities; this catalog does not replace or automatically bind them.",
  definitions: [
    {
      id: "guarantee:scoped-reads", title: "Scoped reads", category: "Authority and privacy",
      promise: "Ordinary reads through the named boundary return only records in the declared effective scope, and missing required context refuses.",
      appliesWhen: "A read entry point promises to restrict a shared population using explicit scope context.",
      parameters: ["read boundary", "population", "effective-scope relation", "context source", "authorized bypasses"],
      excludes: "Raw queries, alternate managers, and explicit cross-scope operations outside the bound entry point; context correctness needs its own evidence.",
      falsifier: "Create records in two scopes; read under one context and observe the other's record, or omit context and obtain an unrestricted read.",
      demoteWhen: "The scope relation cannot distinguish permitted from forbidden records without embedding a new local access policy in the definition.",
      distinctFrom: other("capability-authorization", "Confining a result population does not establish the caller's right to perform the operation."),
      example: controlled(inspected("posthog/models/scoping", "posthog/models/scoping/manager.py", "_apply_team_filter", "posthog/models/scoping/test_manager.py", "test_team_scope_filters_to_team", "Filter removal exposed two rows instead of one. Missing-context test passed but its refusal branch was not mutated. Framework bypasses remain."), r3 + "baseline.xml", r3 + "tenant-mutated.xml", r3 + "tenant-restored.xml"),
    },
    {
      id: "guarantee:capability-authorization", title: "Capability authorization", category: "Authority and privacy",
      promise: "A credential authorizes only its declared resource, operation, audience and validity interval at the named acceptance boundary.",
      appliesWhen: "A service accepts credentials carrying bounded authority.",
      parameters: ["acceptance boundary", "resource identity", "operation set", "audience", "validity and key policy"],
      excludes: "Legacy shared-secret and intentionally unauthenticated branches; authenticity alone does not confer authority.",
      falsifier: "Present a valid read token to a delete operation or another resource and observe acceptance.",
      demoteWhen: "A binding needs mutually incompatible meanings of resource or action that cannot be stated as explicit sets and matching rules.",
      distinctFrom: other("message-authenticity", "An authentic message can still request an unauthorized action."),
      example: inspected("nodejs/src/session-replay", "nodejs/src/session-replay/recording-api/auth.ts", "jwt", "nodejs/src/session-replay/recording-api/auth.test.ts", "describe", "Source-inspected JWT rejection cases; fallback and development paths prevent a blanket route guarantee."),
    },
    {
      id: "guarantee:current-authority", title: "Current authority", category: "Authority and privacy",
      promise: "Deferred or resumed work revalidates the actor's current authority at the declared execution boundary rather than relying solely on queue-time authority.",
      appliesWhen: "An authority-changing interval separates acceptance from execution or resumption.",
      parameters: ["actor", "deferred work", "revalidation point", "authority source", "trusted-system exceptions"],
      excludes: "Revocation of already-running work and remote invalidation of copied credentials; those require separate enforcement.",
      falsifier: "Queue work, revoke membership, then dispatch it successfully without a declared trusted-system exception.",
      demoteWhen: "Queued and resumed examples require different authority times but the binding cannot name which observation controls execution.",
      distinctFrom: other("capability-authorization", "This tests authority changing over time, not only the shape of one accepted credential."),
      example: inspected("products/tasks", "products/tasks/backend/management/commands/run_task_workflow_dispatcher.py", "_user_can_dispatch", "products/tasks/backend/tests/test_workflow_dispatch.py", "membership", "Permission service is mocked in inspected tests. Resume credential-clearing is a second discovery context, not an executed general binding."),
    },
    {
      id: "guarantee:destination-confinement", title: "Destination confinement", category: "Authority and privacy",
      promise: "Outbound payload delivery remains inside the declared destination policy through redirects and other followed hops.",
      appliesWhen: "A sender accepts a destination or follows a response that can change it.",
      parameters: ["sending boundary", "allowed destinations", "redirect policy", "payload and credential scope"],
      excludes: "A URL allowlist alone does not prove DNS-rebinding resistance or confinement of uninspected transports.",
      falsifier: "An allowed initial destination redirects to a forbidden destination and the sender forwards the payload.",
      demoteWhen: "The proposed policy cannot describe actual followed destinations, or merges transport confinement with unrelated actor permissions.",
      distinctFrom: other("scoped-reads", "This confines where data is sent, not which records a read returns."),
      example: inspected("products/batch_exports", "products/batch_exports/backend/temporal/destinations/http_batch_export.py", "allow_redirects=False", null, "", "Two endpoint URLs and disabled redirects were inspected. No matching end-to-end redirect-confinement oracle was located in the bounded search."),
    },
    {
      id: "guarantee:message-authenticity", title: "Message authenticity", category: "Authority and privacy",
      promise: "A message is accepted only if its protected fields verify under the declared signing and trust policy.",
      appliesWhen: "A receiver relies on a signed external message before applying effects.",
      parameters: ["signed fields and canonicalization", "trust anchors", "accepted algorithms", "verification boundary"],
      excludes: "Replay freshness, authorization and truthful content from an authorized signer are not established by signature verification.",
      falsifier: "Change a protected payload field without resigning and observe acceptance.",
      demoteWhen: "The binding cannot enumerate protected fields or distinguish signature validity from authorization and replay policy.",
      distinctFrom: other("capability-authorization", "Authenticity establishes protected-message origin and integrity, not permission to act."),
      example: inspected("products/workflows", "products/workflows/backend/services/sns_verification.py", "verify_sns_message", "products/workflows/backend/test/test_sns_verification.py", "test_rejects", "Tampered payload/topic and invalid signatures are tested with a patched certificate fetch; no live trust-chain or replay assay was run."),
    },
    {
      id: "guarantee:encrypted-storage", title: "Encrypted storage", category: "Authority and privacy",
      promise: "The named persistence boundary encodes protected values as ciphertext under the configured key policy rather than persisting plaintext.",
      appliesWhen: "A field or object is explicitly designated confidential at rest.",
      parameters: ["protected fields", "write boundary", "encryption policy", "key ownership", "allowed plaintext exceptions"],
      excludes: "Logs, process memory, backups, access control and cryptographic algorithm strength outside the declared boundary.",
      falsifier: "Write a synthetic secret through the field and find that plaintext in its raw persisted representation.",
      demoteWhen: "The example only encrypts a helper return value and cannot identify a persistence crossing to bind.",
      distinctFrom: other("redaction", "Encryption preserves recoverability with authority; redaction removes designated content from an output."),
      example: inspected("posthog/helpers", encryption, "get_prep_value", encryptionTest, "test_simple_encryption_and_decryption", "Persistence hook inspected, but the cited test exercises encryption/decryption helpers, not a raw database read. A persistence-crossing oracle remains needed; this is not a census of sensitive fields."),
    },
    {
      id: "guarantee:key-rotation-compatibility", title: "Key rotation compatibility", category: "Authority and privacy",
      promise: "During the declared rotation stages, supported readers can decrypt retained data while new writes use the stage's designated key.",
      appliesWhen: "Encrypted data must survive key changes and coexisting reader versions.",
      parameters: ["rotation stages", "reader key sets", "write key per stage", "retained data population", "retirement point"],
      excludes: "Readability after deliberate removal of the only decrypting key, key compromise recovery and remote credential revocation.",
      falsifier: "Prepend a new write key while retaining the old read key and lose readability of old ciphertext, or write with the wrong stage key.",
      demoteWhen: "The stage model cannot distinguish a supported mixed deployment from deliberate key retirement without bespoke lifecycle clauses.",
      distinctFrom: other("encrypted-storage", "Ciphertext can remain encrypted while a rotation makes it unreadable."),
      example: inspected("posthog/helpers", encryption, "MultiFernet", encryptionTest, "test_prepending_new_key_keeps_old_data_readable_and_writes_with_new", "Multiple-key and two-stage tests inspected; removing an old key intentionally makes its old data unreadable."),
    },
    {
      id: "guarantee:redaction", title: "Policy-scoped redaction", category: "Authority and privacy",
      promise: "Output removes or replaces content designated sensitive by the declared recognition and allowlist policy across the bound representation paths.",
      appliesWhen: "A representation is exported with an explicit scrubbing policy.",
      parameters: ["input representations", "sensitive-content recognizer", "allowlist", "replacement rule", "output boundary"],
      excludes: "Universal PII detection, irreversible anonymization, image/OCR coverage or representations absent from the binding.",
      falsifier: "Place a policy-designated secret in a bound nested representation and observe it unchanged in exported output.",
      demoteWhen: "A binding says all personal data without an enumerable representation population and a concrete recognizer boundary.",
      distinctFrom: other("encrypted-storage", "A scrubbed output must not expose the designated content even to a reader with storage access."),
      example: inspected("rust/replay-anonymizer", "rust/replay-anonymizer/src/text.rs", "scrub_text", "rust/replay-anonymizer/tests/typed.rs", "full_snapshot_parses_to_a_scrubbed_typed_tree", "Typed-tree test checks scrubbed text under an explicit allowlist and requires typed-parse feature; no claim of complete replay anonymization."),
    },
    {
      id: "guarantee:input-validation", title: "Input contract enforcement", category: "Representation and meaning",
      promise: "When the declared validation policy is enabled, invalid inputs do not enter the accepted processing path.",
      appliesWhen: "A boundary has an explicit schema and reject or quarantine behavior.",
      parameters: ["input schema", "enabled modes", "validation boundary", "coercion policy", "rejection outcome"],
      excludes: "Unenforced schemas, unknown types explicitly allowed by policy, optional properties not checked, and semantic authorization.",
      falsifier: "Omit a required field with enforcement enabled and observe the event accepted without its declared rejection outcome.",
      demoteWhen: "The schema/coercion parameters cannot separate invalid data from explicitly permitted unknown or optional values.",
      distinctFrom: other("message-authenticity", "A correctly signed payload may still be structurally invalid."),
      example: inspected("nodejs/src/ingestion", "nodejs/src/ingestion/common/steps/event-preprocessing/validate-event-schema.ts", "validateEventAgainstSchema", "nodejs/src/ingestion/common/steps/event-preprocessing/validate-event-schema.test.ts", "should reject when required property is missing", "Required-property and pipeline drop tests inspected; disabled enforcement and unknown-type permissiveness are intentional exceptions."),
    },
    {
      id: "guarantee:semantic-preservation", title: "Semantic preservation", category: "Representation and meaning",
      promise: "A transformation preserves the declared observable meaning of the reference computation on its supported input domain.",
      appliesWhen: "An optimization or translation claims equivalence to a reference behavior.",
      parameters: ["transformation", "reference semantics", "input domain", "observation relation", "permitted differences"],
      excludes: "Byte identity, performance improvement and equivalence of transformations or query forms outside the bound domain.",
      falsifier: "Push a page limit beneath an aggregate and obtain the page size instead of the full population count.",
      demoteWhen: "The observation relation becomes an opaque local program that restates the entire contract rather than a reviewable equivalence relation.",
      distinctFrom: other("canonical-encoding", "Consistent output can be consistently wrong; semantic preservation compares meaning against a reference."),
      example: inspected("posthog/hogql", "posthog/hogql/database/schema/persons.py", "limit", "posthog/hogql/database/schema/test/test_persons.py", "count", "Inspected persons limit-pushdown regression cases; no exhaustive optimizer equivalence was measured."),
    },
    {
      id: "guarantee:canonical-encoding", title: "Canonical encoding", category: "Representation and meaning",
      promise: "Inputs equivalent under the declared normalization relation produce the same encoded identity regardless of irrelevant representation ordering.",
      appliesWhen: "A key, digest input or serialized identity must ignore representation-only differences.",
      parameters: ["input tuple", "normalization relation", "encoding version", "output identity"],
      excludes: "Cryptographic collision resistance, semantic correctness of the chosen identity and arbitrary input permutations that change meaning.",
      falsifier: "Reorder the same map's entries and obtain a different deduplication key.",
      demoteWhen: "Examples disagree on which differences are irrelevant and the declared normalization cannot express that without changing the promise.",
      distinctFrom: other("duplicate-suppression", "Stable keys do not show that repeated operations are actually suppressed."),
      example: inspected("nodejs/src/ingestion", dedup, "featureFlagCalledDedupKey", dedupTest, "is independent of $groups property ordering", "Tuple encoding and sorted group entries inspected; equality does not establish global collision freedom."),
    },
    {
      id: "guarantee:identity-continuity", title: "Identity continuity", category: "Representation and meaning",
      promise: "A declared identity transition preserves the bound assignment or association while the policy and relevant state remain fixed.",
      appliesWhen: "A system promises continuity across anonymous/identified or other identity changes.",
      parameters: ["identity transition", "preserved assignment", "continuity policy", "fixed state", "reset exceptions"],
      excludes: "Flag revisions, eligibility changes, deliberately disabled continuity and unavailable identity state.",
      falsifier: "Hold flag policy fixed, identify an anonymous user under enabled continuity, and observe rebucketing solely from the identity change.",
      demoteWhen: "The supposedly preserved relationship cannot be separated from mutable policy that intentionally changes the assignment.",
      distinctFrom: other("canonical-encoding", "Continuity preserves a relationship across deliberately different identities, not equivalent input encodings."),
      example: inspected("rust/feature-flags", "rust/feature-flags/src/flags/flag_matching.rs", "hash", "rust/feature-flags/tests/test_experience_continuity.rs", "anonymous", "Source-inspected anonymous hash-key override and disablement cases; not a guarantee that flag results never change."),
    },
    {
      id: "guarantee:revision-preservation", title: "Revision preservation", category: "Representation and meaning",
      promise: "Publishing a new revision preserves the previous revision's bound content and identity instead of rewriting its history.",
      appliesWhen: "A publication path maintains version-addressed history.",
      parameters: ["publication boundary", "revision identity", "content field set", "history retention policy"],
      excludes: "Database-administrator edits, deliberate retention deletion, tamper-proof storage and workers executing historical snapshots.",
      falsifier: "Publish changed content as revision two and observe revision one's content change or disappear without a retention event.",
      demoteWhen: "The binding cannot distinguish historical snapshots from a mutable current-state table, or preservation is already wholly expressed by another retained contract.",
      distinctFrom: other("supersession-safety", "The old revision remains addressable even when a newer revision legitimately becomes current."),
      example: inspected("products/workflows", "products/workflows/backend/api/hog_flow.py", "_append_revisions", "products/workflows/backend/api/test/test_hog_flow_revisions.py", "test_publish_appends_revision_and_bumps_version", "API creates snapshots of outgoing and incoming content. Model remains writable; this is publication-path preservation, not unrepresentable mutation."),
    },
    {
      id: "guarantee:separation-of-duties", title: "Separation of duties", category: "Change control",
      promise: "An actor cannot satisfy mutually exclusive roles in the same protected operation when the declared approval policy forbids it.",
      appliesWhen: "A policy requires independent request and approval authority.",
      parameters: ["operation", "actor identity", "incompatible roles", "policy snapshot", "explicit bypasses"],
      excludes: "Policies allowing self-approval, proof that two accounts belong to different people, and enforcement outside the gated API.",
      falsifier: "With self-approval disabled, let the requester approve its own change through the protected endpoint.",
      demoteWhen: "The rule reduces entirely to ordinary single-role permission checking and no cross-role incompatibility remains.",
      distinctFrom: other("capability-authorization", "An otherwise authorized approver can be ineligible because it also requested this operation."),
      example: inspected("products/approvals", "products/approvals/backend/permissions.py", "allow_self_approve", null, "", "Explicit requester-versus-approver refusal inspected. Bounded API-test search did not establish a focused self-approval negative oracle."),
    },
    {
      id: "guarantee:legal-state-transitions", title: "Legal state transitions", category: "Change control",
      promise: "A transition commits only from a currently allowed predecessor state, rechecked within the serialization boundary.",
      appliesWhen: "Concurrent actors may make competing terminal decisions about one stateful subject.",
      parameters: ["subject", "allowed transition relation", "serialization boundary", "conflict outcome"],
      excludes: "External effects outside the transaction and proof of physical concurrency when an oracle only simulates the locked state.",
      falsifier: "Read a pending request, let another actor reject it, then approve it using the stale pre-lock state.",
      demoteWhen: "The family cannot identify a transition relation distinct from versioned value replacement or ownership fencing.",
      distinctFrom: other("worker-fencing", "This guards legal predecessor states, not a worker's right to commit after losing ownership."),
      example: inspected("products/approvals", "products/approvals/backend/services.py", "select_for_update", "products/approvals/backend/tests/test_services.py", "test_raises_when_state_changed_under_lock", "Test mocks the locked row's changed state; this does not exercise two real database transactions racing."),
    },
    {
      id: "guarantee:supersession-safety", title: "Supersession safety", category: "Concurrency and identity",
      promise: "Late work publishes only while its declared precondition still holds; it cannot displace a superseding accepted value or clean up that winner's resources.",
      appliesWhen: "Asynchronous operations compete to publish state at one subject.",
      parameters: ["publication subject", "operation identity", "supersession relation", "acceptance precondition", "cleanup ownership"],
      excludes: "General linearizability and equal-value intermediate-write detection unless explicitly represented by the precondition.",
      falsifier: "Finish a newer upload first, then an older upload, and observe an obsolete publication or surviving losing resource contrary to the cleanup policy.",
      demoteWhen: "A second context requires changing the supersession relation's meaning or hides the entire publication policy in an opaque predicate.",
      distinctFrom: other("retry-recognition", "Competing operations must not win late; the same already-applied operation must still recognize its own success."),
      example: controlled(inspected("posthog/query_cache", cacheScript, "REPLACE_IF_UNCHANGED_SCRIPT", cacheTest, "test_stale_upload_cannot_replace_a_newer_entry", "Removing the mismatch refusal fails on two remaining fake-storage objects. The later newer-response assertion is not reached in that mutant. Real Redis, controlled uploads, fake S3."), r3 + "baseline.xml", r3 + "cache-mutated.xml", r3 + "cache-restored.xml"),
    },
    {
      id: "guarantee:retry-recognition", title: "Already-applied retry recognition", category: "Concurrency and identity",
      promise: "Repeating an operation whose own effect already landed recognizes that success rather than classifying the retry as a conflicting operation.",
      appliesWhen: "Replies can be lost and the caller retries a distinguishable operation.",
      parameters: ["operation identity", "already-applied witness", "retry horizon", "success result", "cleanup consequence"],
      excludes: "Exactly-once execution, detection of every network failure, and retry identities reused by unrelated operations.",
      falsifier: "Install an operation's pointer, repeat its swap with the old expected bytes, and receive a conflict result that would trigger losing-upload cleanup.",
      demoteWhen: "The implementation cannot identify its own prior effect independently of a coincidentally equal foreign effect.",
      distinctFrom: other("duplicate-suppression", "Recognizing success may permit redelivery; suppressing every retry can instead lose unfinished downstream work."),
      example: controlled(inspected("posthog/query_cache", cacheScript, "REPLACE_IF_UNCHANGED_SCRIPT", cacheTest, "test_stale_upload_cannot_replace_a_newer_entry", "Deleting already-applied recognition fails on False versus True at the retry assertion. No actual lost network reply was injected."), r3 + "cache-restored.xml", r3 + "retry-mutated.xml", r3 + "final.xml"),
    },
    {
      id: "guarantee:duplicate-suppression", title: "Identity-scoped duplicate suppression", category: "Concurrency and identity",
      promise: "Within the declared horizon, competing claims for one deduplication identity receive the declared suppression outcome while permitted redelivery remains distinct.",
      appliesWhen: "A boundary explicitly deduplicates logical events or requests.",
      parameters: ["deduplication tuple", "claim identity", "retention horizon", "suppressed effect", "store-failure policy"],
      excludes: "Global exactly-once processing, repeats after expiry and suppression during an explicitly fail-open store outage.",
      falsifier: "Claim the same identity with two foreign operation IDs within the live window and accept both despite healthy deduplication storage.",
      demoteWhen: "The effect and identity cannot be named precisely enough to separate duplicates from permitted retries.",
      distinctFrom: other("retry-recognition", "Different claims for one logical event are not the same operation retrying its own effect."),
      example: inspected("nodejs/src/ingestion", dedup, "claimKeys", dedupTest, "maps fresh claims to true and foreign claims to false", "Mocked Redis pipeline cases include own redelivery and fail-open errors. Not a downstream exactly-once result."),
    },
    {
      id: "guarantee:keyed-ordering", title: "Keyed ordering", category: "Concurrency and identity",
      promise: "The named transport boundary retains the routing key required by the declared ordering domain and lane.",
      appliesWhen: "Routing promises ordered handling for a specific identity, not global traffic.",
      parameters: ["ordering identity", "sequence definition", "lane policy", "transport boundary", "routing key"],
      excludes: "Total global order and downstream order across producer failures, rebalances or storage unless separately bound.",
      falsifier: "Choose an ordered lane but emit its records without the required key, or derive the key policy from a contradictory header.",
      demoteWhen: "The proposed binding conflates key preservation with observed end-to-end processing order.",
      distinctFrom: other("fair-admission", "Preserving a stream's order says nothing about service order among competing streams."),
      example: inspected("rust/capture", "rust/capture/src/pipeline.rs", "OrderingGuarantee", "rust/capture/src/v1/sinks/kafka/sink_tests.rs", "ordering_decides_partition_key", "Routing and sink-key tests inspected; actual multi-producer ordering was not executed."),
    },
    {
      id: "guarantee:worker-fencing", title: "Stale worker fencing", category: "Concurrency and identity",
      promise: "After ownership changes, work carrying the former ownership generation cannot commit through the fenced boundary.",
      appliesWhen: "Workers may complete after a lease, assignment or ownership handoff.",
      parameters: ["owned partition or resource", "ownership generation", "handoff point", "fenced commit", "retained-ownership policy"],
      excludes: "Side effects outside the offset/store fence and proof that every worker operation checks the generation.",
      falsifier: "Revoke a partition, finish its old batch after the drain budget, and observe its late offsets committed by the former owner.",
      demoteWhen: "The binding cannot distinguish loss of authority from ordinary competing values or cannot locate the actual commit fence.",
      distinctFrom: other("supersession-safety", "Fencing invalidates an owner's right to commit even if no newer value has been published."),
      example: inspected("nodejs/src/common/kafka", "nodejs/src/common/kafka/consumer/consumer-v2.ts", "dispatchEpochs", "nodejs/src/common/kafka/consumer/consumer-v2.rebalance.integration.serial.test.ts", "a batch outliving the drain budget is fenced", "Partition epoch comparison and rebalance oracle inspected; broker-backed suite not run in this catalog pass."),
    },
    {
      id: "guarantee:acknowledgment-barrier", title: "Acknowledgment barrier", category: "Delivery and recovery",
      promise: "Successful acknowledgment follows the named completion barrier rather than mere receipt or submission.",
      appliesWhen: "A producer relies on an acknowledgment to retire responsibility for submitted work.",
      parameters: ["work identity", "completion barrier", "success acknowledgment", "barrier failure outcome"],
      excludes: "Durability, query visibility and downstream exactly-once behavior not promised by that barrier.",
      falsifier: "Hold settlement unresolved and observe successful acknowledgment or retirement of its in-flight responsibility.",
      demoteWhen: "The binding uses completed without specifying which event retires which responsibility.",
      distinctFrom: other("commit-ordered-effects", "This delays reporting success; commit ordering delays issuing an external effect."),
      example: controlled(inspected("nodejs/src/ingestion", grpc, "settleAndAck", grpcTest, "records an accepted sub-batch in the shared in-flight metrics until it settles", "Removing await caused named in-flight and independent-settlement failures. These are observed related assertions, not a direct proof of Kafka durability or every early-ack schedule."), r2 + "ack-restored.json", r2 + "ack-mutated.json", r2 + "ack-final.json"),
    },
    {
      id: "guarantee:commit-ordered-effects", title: "Commit-ordered side effects", category: "Delivery and recovery",
      promise: "An irreversible external effect is not issued before the transaction establishing its intent successfully commits.",
      appliesWhen: "A transaction creates state whose existence authorizes external work.",
      parameters: ["transaction", "intent", "external effect", "dispatch boundary"],
      excludes: "Eventual delivery after commit and effects issued on other code paths.",
      falsifier: "Roll back creation after registering dispatch and observe the external workflow start anyway.",
      demoteWhen: "A candidate cannot separate the commit precondition from an unsupported promise that all committed work eventually runs.",
      distinctFrom: other("durable-dispatch-intent", "Waiting until commit avoids premature effects but can still lose the post-commit callback."),
      example: inspected("products/tasks", "products/tasks/backend/models.py", "on_commit", "products/tasks/backend/tests/test_workflow_dispatch.py", "dispatch", "Atomic creation and post-commit scheduling inspected. Dispatch tests are broader evidence candidates, not a claimed executed rollback oracle."),
    },
    {
      id: "guarantee:durable-dispatch-intent", title: "Durable dispatch intent", category: "Delivery and recovery",
      promise: "Committed work retains a discoverable dispatch intent until the declared dispatch acknowledgment retires it, including loss of the immediate callback.",
      appliesWhen: "A database commit and external dispatch cannot be one atomic operation.",
      parameters: ["intent record", "commit boundary", "discovery mechanism", "retirement evidence", "retention policy"],
      excludes: "Unconditional eventual delivery, an operating dispatcher, permanent downstream availability and exactly-once execution.",
      falsifier: "Commit a run, lose its immediate callback, and find no recoverable dispatch intent for the scanner.",
      demoteWhen: "The only implementation evidence is a callback with no retained discoverable intent, or a liveness claim cannot name its operating assumptions.",
      distinctFrom: other("commit-ordered-effects", "A safely ordered callback is still lossy if no durable intent survives its loss."),
      example: inspected("products/tasks", "products/tasks/backend/logic/services/workflow_dispatch.py", "def create_dispatch", "products/tasks/backend/tests/test_workflow_dispatch.py", "pending_dispatch", "Stored dispatch options and markers inspected. This measures recoverability of intent, not delivery under arbitrary outages."),
    },
    {
      id: "guarantee:resumption-coverage", title: "Resumption without omissions", category: "Delivery and recovery",
      promise: "After interruption, planned remaining work covers the required range not already completed under the declared boundary and overlap rules.",
      appliesWhen: "A batch operation resumes from completed ranges or checkpoints.",
      parameters: ["required population or interval", "checkpoint semantics", "range boundary rules", "allowed overlap", "source-change policy"],
      excludes: "Exactly-once downstream effects and records arriving outside the bound source snapshot or interval policy.",
      falsifier: "Supply overlapping completed ranges and observe a required uncovered interval omitted from the resumed plan.",
      demoteWhen: "The population is moving but no source-change or snapshot policy can state what must be covered.",
      distinctFrom: other("duplicate-suppression", "Coverage prevents omissions; overlap may be intentional and does not itself promise duplicate-free effects."),
      example: inspected("products/batch_exports", "products/batch_exports/backend/temporal/batch_exports.py", "generate_query_ranges", "products/batch_exports/backend/tests/temporal/test_batch_exports.py", "test_generate_query_ranges", "Range-planning tests inspected, not an end-to-end interrupted export against every destination."),
    },
    {
      id: "guarantee:retry-classification", title: "Retry classification", category: "Delivery and recovery",
      promise: "Failures are classified as retryable or terminal according to the declared error policy, without silently exchanging those outcomes.",
      appliesWhen: "A worker chooses whether to retry after an external failure.",
      parameters: ["error domain", "retry policy", "terminal outcome", "unknown-error policy"],
      excludes: "Backoff, attempt bounds, successful recovery and universal meanings for particular HTTP status codes.",
      falsifier: "Return an error declared terminal and observe another retry, or return a declared transient error and observe premature termination.",
      demoteWhen: "The catalog bakes one destination's status-code mapping into the supposedly reusable definition.",
      distinctFrom: other("retry-recognition", "Eligibility to retry is independent of recognizing an effect that already landed."),
      example: inspected("products/batch_exports", "products/batch_exports/backend/temporal/destinations/http_batch_export.py", "429", "products/batch_exports/backend/tests/temporal/destinations/test_http_batch_export_workflow.py", "429", "400 versus 429/500 cases inspected; exact mapping is destination policy, not a universal guarantee."),
    },
    {
      id: "guarantee:graceful-drain", title: "Graceful drain", category: "Delivery and recovery",
      promise: "Shutdown stops the declared admission path and gives already-accepted work its promised settlement/drain opportunity before closing, with an explicit deadline outcome.",
      appliesWhen: "A service closes while work is in flight.",
      parameters: ["admission stop point", "accepted-work population", "completion criterion", "drain budget", "timeout outcome"],
      excludes: "Unbounded waiting, guaranteed completion of stalled dependencies and work outside the captured drain population.",
      falsifier: "Initiate stop with a settling accepted batch and observe its stream closed before its acknowledgment within the allowed drain budget.",
      demoteWhen: "The definition cannot state which work was accepted before shutdown or treats forced timeout as successful completion.",
      distinctFrom: other("acknowledgment-barrier", "A per-work acknowledgment rule does not ensure shutdown keeps its transport alive long enough to deliver it."),
      example: inspected("nodejs/src/ingestion", grpc, "async stop", grpcTest, "stop() drains in-flight sub-batch acks before ending streams", "Original test body inspected; R2 ran the enclosing suite, but no drain-specific mutation is claimed here."),
    },
    {
      id: "guarantee:cancellation-release", title: "Cancellation releases capacity", category: "Resources and resilience",
      promise: "Canceled waiting work loses its queue claim and any subsequently granted capacity is returned rather than consumed by dead work.",
      appliesWhen: "Cancelable work waits for a scarce slot.",
      parameters: ["waiter identity", "cancel signal", "queue", "capacity ownership", "grant/cancel race rule"],
      excludes: "Stopping already-running server computation and removing already-issued irreversible effects.",
      falsifier: "Cancel a queued waiter, release one slot, and observe the dead waiter consume it while a live waiter remains blocked.",
      demoteWhen: "The supposed cancellation property only hides presentation and has no queue or resource claim to release.",
      distinctFrom: other("fair-admission", "A FIFO queue can be fair among live entries yet leak every canceled entry's capacity."),
      example: inspected("nodejs/src/ingestion", grpc, "class FifoSlots", grpcTest, "drops a cancelled stream from the admission queue", "Controlled queue cancellation test inspected; no assertion that remote computation is terminated."),
    },
    {
      id: "guarantee:bounded-admission", title: "Bounded admission", category: "Resources and resilience",
      promise: "The named admission boundary does not admit more simultaneously active work than its configured capacity.",
      appliesWhen: "A scheduler or service imposes a concurrency ceiling.",
      parameters: ["admission boundary", "counted active unit", "capacity", "overflow behavior", "release event"],
      excludes: "Bounds on every buffer, memory allocation, per-tenant fairness and time-window rate limits.",
      falsifier: "Keep the configured number of streams active and successfully admit an additional stream instead of applying overflow policy.",
      demoteWhen: "No observable counted active unit exists, or the candidate conflates instantaneous concurrency with cumulative rate.",
      distinctFrom: other("rate-budget", "Concurrency counts active work; a rate budget counts consumption over time even after work finishes."),
      example: inspected("nodejs/src/ingestion", grpc, "maxStreams", grpcTest, "refuses a stream past the total concurrency ceiling", "Total stream ceiling test inspected; not a bound on every queue or allocation in ingestion."),
    },
    {
      id: "guarantee:fair-admission", title: "Fair admission", category: "Resources and resilience",
      promise: "When capacity becomes available, eligible contenders receive service according to the declared scheduling order rather than accidental races.",
      appliesWhen: "Multiple eligible contenders share a scheduling resource with an explicit fairness policy.",
      parameters: ["contender identity", "eligibility", "scheduling order", "resource", "progress assumptions"],
      excludes: "Wall-clock latency bounds, equal throughput and progress while no slots become available.",
      falsifier: "Queue A before B under FIFO policy, free a slot, and grant it to B while A remains eligible.",
      demoteWhen: "Fairness cannot be expressed as a concrete service-order relation with explicit progress assumptions.",
      distinctFrom: other("bounded-admission", "A capacity-safe scheduler can indefinitely favor the same contender."),
      example: inspected("nodejs/src/ingestion", grpc, "class FifoSlots", grpcTest, "grants feed slots in arrival order across streams", "FIFO test inspected; this does not establish starvation freedom under arbitrary stalled dependencies."),
    },
    {
      id: "guarantee:rate-budget", title: "Identity-scoped rate budget", category: "Resources and resilience",
      promise: "Admission accounts for weighted consumption against every declared time window of the correct budget owner.",
      appliesWhen: "Requests share an external or internal quota over time.",
      parameters: ["budget owner", "request weight", "window limits", "clock", "storage failure policy", "priority reserves"],
      excludes: "Fleet-wide enforcement during per-process fallback and upstream limits omitted from the configured policy.",
      falsifier: "Exhaust a short window while a longer one has room and still admit work, or charge one owner's requests against another's budget.",
      demoteWhen: "A binding cannot identify the real external budget owner, or claims fleet-wide enforcement while its failure policy only enforces per-process limits.",
      distinctFrom: other("bounded-admission", "Completed requests still consume the time-window allowance."),
      example: inspected("posthog/egress", "posthog/egress/limiter/outbound.py", "consume_sync", "posthog/egress/test/test_outbound_rate_limiter.py", "test_budget_denies_once_exhausted", "Weighted and multiwindow tests inspected, including independent keys. Redis failure deliberately falls back to memory, narrowing enforcement scope."),
    },
    {
      id: "guarantee:memory-budget", title: "Accounted memory budget", category: "Resources and resilience",
      promise: "The bound evaluator refuses further accounted allocation once its declared memory budget would be exceeded.",
      appliesWhen: "Untrusted or variable-sized work runs under explicit allocation accounting.",
      parameters: ["evaluator", "accounted allocation domain", "measurement unit", "limit", "overflow outcome"],
      excludes: "Operating-system RSS, unaccounted host-library allocations and a claim that all memory is bounded.",
      falsifier: "Execute an allocation-growing program and observe accounted allocation exceed the budget without the declared refusal.",
      demoteWhen: "The budget is presented as total process memory while only VM stack values are counted, or no accounted domain can be stated.",
      distinctFrom: other("execution-budget", "A short computation can allocate too much; a small-memory computation can perform too much work."),
      example: inspected("common/hogvm", vm, "Memory limit of", vmTest, "memory limits 1", "VM allocation-accounting failure assertions inspected; not a hard bound on JavaScript process RSS."),
    },
    {
      id: "guarantee:execution-budget", title: "Execution step budget", category: "Resources and resilience",
      promise: "Execution refuses further counted steps once the declared operation budget is exhausted.",
      appliesWhen: "An interpreter or workflow permits bounded repeated execution or external calls.",
      parameters: ["execution identity", "counted step", "budget", "resume accounting", "exhaustion outcome"],
      excludes: "A wall-clock deadline, memory limits and operations the declared counter does not count.",
      falsifier: "Run a program requesting more than the allowed asynchronous steps and observe another counted call after exhaustion.",
      demoteWhen: "The counted unit cannot be identified, or the binding calls a step cap a time bound without evidence.",
      distinctFrom: other("memory-budget", "Work can exceed its step budget without growing its memory footprint."),
      example: inspected("common/hogvm", vm, "Exceeded maximum number of async steps", vmTest, "async limits", "Original tests request 200 async steps and require refusal at configured caps of 100 and 55; tests inspected, not executed this round."),
    },
    {
      id: "guarantee:circuit-breaker-policy", title: "Circuit-breaker policy", category: "Resources and resilience",
      promise: "Observed dependency failures produce the declared open/closed and bypass decision under the configured sample window and threshold policy.",
      appliesWhen: "A caller uses failure history to divert or suppress calls to a struggling dependency.",
      parameters: ["dependency", "sample window", "minimum sample", "failure threshold", "bypass policy", "disabled and store-failure behavior"],
      excludes: "Zero traffic to an open circuit when bypass is probabilistic, caller compliance and downstream recovery.",
      falsifier: "Reach the configured failure threshold with sufficient samples and observe a closed decision, or include expired samples against policy.",
      demoteWhen: "The definition conflates a breaker decision with transport enforcement or hides probabilistic bypass behind a zero-traffic claim.",
      distinctFrom: other("rate-budget", "Failure observations determine this decision; healthy request volume alone does not."),
      example: inspected("services/llm-gateway", "services/llm-gateway/src/llm_gateway/circuit_breaker.py", "async def evaluate", "services/llm-gateway/tests/test_circuit_breaker.py", "test_opens_when_failure_rate_crosses_threshold", "Windowed statistics and threshold assertions inspected. Caller must honor opt-in; bypass is probabilistic and missing Redis is inert."),
    },
    {
      id: "guarantee:readiness-evidence", title: "Readiness requires current evidence", category: "Evidence and population",
      promise: "A readiness claim requires current positive observations of every declared serving prerequisite, not merely a live process.",
      appliesWhen: "A deployment or router admits traffic based on a readiness surface.",
      parameters: ["readiness boundary", "prerequisite registry", "observation freshness", "failure outcome"],
      excludes: "Undeclared dependencies, all possible request success and liveness, which may intentionally remain true during dependency failure.",
      falsifier: "Revoke a required database grant and observe the next readiness probe report ready.",
      demoteWhen: "The prerequisite population is implicit or the definition cannot distinguish readiness from process liveness.",
      distinctFrom: other("completion-evidence", "Readiness is a renewable precondition for serving future work, not completion of one past operation."),
      example: inspected("services/llm-gateway", "services/llm-gateway/src/llm_gateway/api/health.py", "async def readiness", "services/llm-gateway/tests/test_health.py", "test_readiness_fails_when_privileges_missing", "Tests mock the DB and require 503 for missing grants; another assertion checks the full REQUIRED_TABLES population."),
    },
    {
      id: "guarantee:declared-target-coverage", title: "Declared target coverage", category: "Evidence and population",
      promise: "A fan-out operation accounts for every target in its declared live registry and refuses unsupported reachability instead of silently omitting a target.",
      appliesWhen: "Work must reach a registry-defined set of stores, clusters or handlers.",
      parameters: ["target registry", "alias identity", "dispatch capability", "required target set", "unreachable outcome"],
      excludes: "Proof that the registry contains every physical copy, backup, external destination or future replay source.",
      falsifier: "Add a declared target outside the dispatcher's reachable clusters and observe it silently skipped while the sweep proceeds as complete.",
      demoteWhen: "The definition treats complete traversal of a list as evidence that the list itself includes every required real-world target.",
      distinctFrom: other("completion-evidence", "Reaching every declared target does not establish that the requested effect occurred there."),
      example: inspected("posthog/models/deletion", "posthog/models/deletion_targets.py", "dispatch", "posthog/models/test/test_deletion_targets.py", "cluster", "Cluster placement, aliases and dispatch refusal inspected. Registry completeness relative to all real copies remains unproved."),
    },
    {
      id: "guarantee:completion-evidence", title: "Completion requires outcome evidence", category: "Evidence and population",
      promise: "A work item enters completed only after the declared observer confirms the requested outcome across its bound target population.",
      appliesWhen: "Submitting or queuing work can precede its actual effect.",
      parameters: ["work item", "required outcome", "observer", "target population", "predicate", "observation time"],
      excludes: "Permanent no-resurrection, deletion of undeclared copies and exact predicate support where the observer uses a conservative superset.",
      falsifier: "Leave a matching event in a required target and observe the deletion request promoted from queued to completed.",
      demoteWhen: "The completion observer only reports that work was submitted, or its observation population cannot be bound separately from the whole project.",
      distinctFrom: other("declared-target-coverage", "Enumerating all destinations is necessary but does not confirm the requested result at any one destination."),
      example: inspected("posthog/models/deletion", "posthog/models/data_deletion_request.py", "verify_queued_request", "posthog/dags/tests/test_data_deletion_requests.py", "test_verify_queued_request_keeps_status_when_events_remain", "Deferred event-deletion verification counts remaining events before promotion. This does not establish backups or no-resurrection."),
    },
  ],
};
