import React, { memo, useCallback, useEffect, useId, useMemo, useRef, useState } from 'react';
import { Background, Controls, EdgeLabelRenderer, Handle, Position, ReactFlow, getViewportForBounds, useReactFlow } from '@xyflow/react';
import { buildStructureModel } from './structure-model.ts';
import { DEFAULT_STRUCTURE_OPTIONS } from './structure-contract.ts';
import { createStructureRegistry, validateLayout, validateRanked, validateRoutes } from './structure-browser/registry.mjs';
import { defaultRank } from './structure-browser/ranking.mjs';
import { defaultBrowserLayout } from './structure-browser/browser-layout.mjs';
import { defaultRoute } from './structure-browser/defaults.mjs';
import { intersects, wrap } from './structure-browser/routing.mjs';
import { StructureSidebar as StructureInspector } from './structure-inspector.jsx';
import './structure-browser/structure.css';

const states = new Map();
const palette = ['#287e85', '#7765a5', '#b27931'];
const Ports = () => ['left', 'right', 'top', 'bottom'].map(side => <React.Fragment key={side}><Handle type="source" position={Position[side[0].toUpperCase() + side.slice(1)]} id={`s-${side}`}/><Handle type="target" position={Position[side[0].toUpperCase() + side.slice(1)]} id={`t-${side}`}/></React.Fragment>);

export function DefaultStructureCard({ card, options, onSelect, onToggle, selected, detail }) {
  return <><button data-structure-card-body={card.id} data-detail={detail} className="structure-card-body nodrag" onClick={() => onSelect(card.id)} aria-label={`Inspect ${card.label}`}>
    <h2>{card.label}</h2>
    {card.downtown && options.cardFields.includes('intent') && <p className="structure-zoom-intent">{card.intent || 'No declared purpose is available.'}</p>}
    {options.cardFields.includes('rationale') && <p className="structure-zoom-rationale">{card.rationale || 'No rationale is declared.'}</p>}
    {options.cardFields.includes('boundaries') && <p className="structure-zoom-rationale">{card.boundaries.length} boundaries</p>}
    {options.cardFields.includes('resources') && <p className="structure-zoom-rationale">{card.resources.length} resources</p>}
    {options.cardFields.includes('entrances') && <p className="structure-zoom-rationale">{card.entrances.length} entrances</p>}
    <span>{card.counts.guarantees} promises · {card.counts.peers} connected components</span></button>
    <button data-structure-unfurl={card.id} className="structure-unfurl nodrag" aria-expanded={card.open} onClick={() => card.guarantees.length ? onToggle(card.id) : onSelect(card.id)}>{card.open ? '− Fold stack' : card.guarantees.length ? '+ Unfurl promises' : 'Inspect responsibility'}</button></>;
}

const StackNode = memo(function StackNode({ data }) {
  const { card, Card, ...props } = data;
  return <article data-structure-stack={card.id} data-downtown={card.downtown} data-open={card.open} className={`structure-stack ${card.downtown ? 'downtown' : 'periphery'} ${props.selected ? 'selected' : ''}`} style={{ width: card.width, height: card.height, '--district': props.color }}><Ports/><Card card={card} {...props}/></article>;
});
const TerminalNode = memo(function TerminalNode({ data }) { const { card, onSelect, selected } = data; return <button data-structure-terminal={card.id} data-guarantee={card.guaranteeId} className={`structure-terminal nodrag ${selected ? 'selected' : ''}`} style={{ width: card.width, height: card.height }} title={card.guaranteeLabel} onClick={() => onSelect(card.guaranteeId)}><Ports/><small>GUARANTEE</small><span>{card.label}</span></button>; });
const PromiseNode = memo(function PromiseNode({ data }) { const { card, onSelect, selected } = data; return <article data-structure-promise-card={card.id} data-owner={card.owner} className={`structure-promise ${card.reliedOn ? 'consumed' : ''} ${selected ? 'selected' : ''}`} style={{ width: card.width, height: card.height }}><Ports/><button className="nodrag" onClick={() => onSelect(card.id)}><small>{card.terminal ? `${card.terminal.label} · ${card.ownerLabel}` : `PROMISE · ${card.ownerLabel}`}</small><span>{card.label}</span><em>{card.reliedOn ? 'Detail of the connected guarantee terminal' : 'Declared responsibility'}</em></button></article>; });
const EntranceNode = memo(function EntranceNode({ data }) { const { card, onSelect } = data; return <button data-structure-entrance={card.id} className="structure-entrance nodrag" style={{ width: card.width, height: card.height }} onClick={() => onSelect(card.owner)}><strong>ENTRY POINT</strong><span>{card.label}</span><svg width={card.width} height={card.height}><defs><marker id="structure-entry-arrow" markerWidth="10" markerHeight="10" refX="8" refY="5" orient="auto"><path d="M0,0 L10,5 L0,10 z"/></marker></defs><path d={`M ${card.width / 2} 96 L ${card.width / 2} ${card.height - 7}`} markerEnd="url(#structure-entry-arrow)"/></svg></button>; });
const EndpointNode = memo(function EndpointNode({ data }) { return <article data-structure-endpoint={data.card.id} className="structure-endpoint"><Ports/><strong>Unresolved endpoint</strong><span>{data.card.label}</span><p>The declaration remains inspectable.</p></article>; });
const ProjectNode = memo(function ProjectNode({ data }) { return <button data-structure-project-entry={data.card.id} className="structure-project-entry nodrag" onClick={() => data.onSelect(data.card.id)}><Ports/><small>PROJECT FRAME</small><strong>{data.card.label}</strong></button>; });

function RoutedEdge({ data }) {
  const { edge, selected, onSelect } = data, mask = `route-${useId().replace(/[^a-z0-9]/gi, '')}`;
  return <><path d={edge.path} className="structure-route-halo"/><path data-structure-route={edge.id} d={edge.path} className={`structure-route ${edge.kind} ${selected ? 'active' : ''}`} markerEnd={edge.kind === 'ownership' || edge.kind === 'continuation' ? undefined : 'url(#structure-arrow)'}/>{edge.labelBox && <EdgeLabelRenderer><button data-structure-route-label={edge.id} className="structure-route-label nodrag nopan" style={{ transform: `translate(${edge.labelBox.x}px,${edge.labelBox.y}px)`, width: edge.labelBox.width, height: edge.labelBox.height }} onClick={() => onSelect(edge.id)}>{edge.labelBox.lines.map((line, index) => <React.Fragment key={`${mask}-${index}`}>{index ? <br/> : null}{line}</React.Fragment>)}</button></EdgeLabelRenderer>}</>;
}
const nodeTypes = { stack: StackNode, terminal: TerminalNode, promise: PromiseNode, entrance: EntranceNode, endpoint: EndpointNode, project: ProjectNode };
const edgeTypes = { routed: RoutedEdge };

function snapshotKey(catalog) { return `${catalog.project ?? 'project'}:${catalog.capturedAt ?? catalog.sources?.map(source => `${source.id}:${source.status}`).join('|') ?? 'snapshot'}`; }
function detailAt(zoom, options, previous = 'detail') { return zoom < options.tileZoom ? 'tile' : zoom > options.detailZoom ? 'detail' : previous; }
function architectureOpening(model, coreIds) {
  const architecture = model.relationships.filter(edge => edge.kind === 'architecture'), result = new Set(architecture.filter(edge => coreIds.includes(edge.source) && coreIds.includes(edge.target)).map(edge => edge.id));
  for (const entrance of model.project.entrances) {
    const start = `component:${entrance.attributes.component}`, queue = [{ id: start, path: [] }], seen = new Set([start]);
    while (queue.length) { const item = queue.shift(); if (coreIds.includes(item.id)) { item.path.forEach(id => result.add(id)); break; } for (const edge of architecture.filter(edge => edge.source === item.id || edge.target === item.id)) { const id = edge.source === item.id ? edge.target : edge.source; if (!seen.has(id)) { seen.add(id); queue.push({ id, path: [...item.path, edge.id] }); } } }
  }
  return result;
}

function DefaultStructureView({ catalog, view, onSelect, selected: externalSelected, onClose, registry, options, implementations }) {
  const model = useMemo(() => buildStructureModel(catalog), [catalog]);
  const key = `${snapshotKey(catalog)}:${view.id}`, cached = states.get(key) ?? {};
  const [selected, setSelected] = useState(externalSelected ?? cached.selected ?? null), [expanded, setExpanded] = useState(() => new Set(cached.expanded ?? []));
  const [mode, setMode] = useState(cached.mode ?? options.initialRelationshipLayer), [focus, setFocus] = useState(cached.focus ?? null), [zoom, setZoom] = useState(cached.viewport?.zoom ?? 1), [detail, setDetail] = useState(cached.detail ?? 'detail');
  const flow = useRef(null), promiseReservations = useRef({ key: '', values: new Map() }), choose = useCallback(id => { setSelected(id); onSelect?.(id); }, [onSelect]);
  useEffect(() => { if (externalSelected !== undefined) setSelected(externalSelected); }, [externalSelected]);
  const ranked = useMemo(() => validateRanked(implementations.rank({ model, options, defaults: registry.defaults }), model), [model, options, registry, implementations]);
  const layout = useMemo(() => validateLayout(implementations.layout({ model, ranked, options, defaults: registry.defaults }), ranked), [model, ranked, options, registry, implementations]);
  const reservationKey = `${key}:${JSON.stringify(options)}:${layout.cards.map(card => `${card.id}:${card.x}:${card.y}:${card.width}:${card.height}`).join('|')}`;
  if (promiseReservations.current.key !== reservationKey) promiseReservations.current = { key: reservationKey, values: new Map() };
  const geometryCards = useMemo(() => layout.cards.map(card => ({ ...card, baseHeight: card.baseHeight ?? card.height })), [layout.cards]);
  const baseCards = useMemo(() => geometryCards.map(card => ({ ...card, open: expanded.has(card.id) })), [geometryCards, expanded]);
  const projectEntry = useMemo(() => layout.root && !geometryCards.some(card => card.id === layout.root.id) && (layout.root.entrances.length || model.relationships.some(edge => edge.source === layout.root.id || edge.target === layout.root.id)) ? { ...layout.root, nodeKind: 'project', x: Math.min(...geometryCards.map(card => card.x), 440) - 380, y: geometryCards.length ? geometryCards.reduce((sum, card) => sum + card.y, 0) / geometryCards.length : 330, width: 260, height: 100 } : null, [layout.root, geometryCards, model.relationships]);
  const fixedCards = useMemo(() => projectEntry ? [...geometryCards, projectEntry] : geometryCards, [geometryCards, projectEntry]);
  const terminalCards = useMemo(() => geometryCards.flatMap(owner => { const ids = [...new Set(model.relationships.filter(edge => edge.kind === 'guarantee-reliance' && edge.target === owner.id).flatMap(edge => edge.guaranteeIds))].sort(); return ids.map((id, index) => { const guarantee = owner.guarantees.find(item => item.id === id); if (!guarantee) return null; const width = Math.min(190, (owner.width - 12 * (ids.length - 1)) / ids.length); return { id: `terminal:${id}`, nodeKind: 'terminal', owner: owner.id, guaranteeId: id, label: options.shortTerminalNames[guarantee.label] ?? guarantee.label, guaranteeLabel: guarantee.label, relationshipIds: model.relationships.filter(edge => edge.kind === 'guarantee-reliance' && edge.target === owner.id && edge.guaranteeIds.includes(id)).map(edge => edge.id), x: owner.x + (owner.width - (width * ids.length + 12 * (ids.length - 1))) / 2 + index * (width + 12), y: owner.y - 62, width, height: 54 }; }).filter(Boolean); }), [geometryCards, model.relationships, options.shortTerminalNames]);
  const annotations = useMemo(() => model.project.entrances.map(entrance => { const owner = fixedCards.find(card => card.id === `component:${entrance.attributes.component}` || card.id === entrance.attributes.component); return owner ? { ...entrance, nodeKind: 'entrance', owner: owner.id, x: owner.x + owner.width / 2 - 150, y: owner.y - 190, width: 300, height: 190 } : null; }).filter(Boolean), [model.project.entrances, fixedCards]);
  const openingIds = useMemo(() => architectureOpening(model, layout.coreIds), [model, layout.coreIds]);
  const externalRelationships = useMemo(() => model.relationships.map(edge => { if (edge.kind !== 'guarantee-reliance') return { ...edge, priority: openingIds.has(edge.id) ? 1 : 0 }; const terminal = terminalCards.find(card => card.owner === edge.target && edge.guaranteeIds.includes(card.guaranteeId)); return terminal ? { ...edge, target: terminal.id, declaredTarget: edge.target, priority: openingIds.has(edge.id) ? 1 : 0, targetPort: { x: Math.round((terminal.x + terminal.width / 2) / 10) * 10, y: terminal.y, side: 'top', dx: 0, dy: -1, lead: 36 } } : { ...edge, priority: openingIds.has(edge.id) ? 1 : 0 }; }), [model.relationships, terminalCards, openingIds]);
  const externalEndpointIds = [...new Set(externalRelationships.flatMap(edge => [edge.source, edge.target]).filter(id => ![...fixedCards, ...terminalCards].some(card => card.id === id)))];
  const endpoints = useMemo(() => externalEndpointIds.map((id, index) => ({ id, nodeKind: 'endpoint', label: id, x: layout.bounds.x + layout.bounds.width + 40, y: layout.bounds.y + 80 + index * 170, width: 228, height: 138 })), [externalEndpointIds.join('\0'), layout.bounds]);
  const baseRouting = useMemo(() => { try { return { routes: validateRoutes(implementations.route({ cards: [...fixedCards, ...terminalCards, ...endpoints], relationships: externalRelationships, annotations, fixedLabels: [], options, defaults: registry.defaults }), externalRelationships), error: null }; } catch (error) { return { routes: [], error: error instanceof Error ? error.message : String(error) }; } }, [fixedCards, terminalCards, externalRelationships, annotations, endpoints, options, registry, implementations]);
  const baseLabels = baseRouting.routes.map(edge => edge.labelBox).filter(Boolean);
  const routeSamples = baseRouting.routes.flatMap(edge => edge.points.map(point => ({ ...point, width: 1, height: 1 })));
  const promiseCards = useMemo(() => [...expanded].flatMap(ownerId => { if (promiseReservations.current.values.has(ownerId)) return promiseReservations.current.values.get(ownerId); const owner = baseCards.find(card => card.id === ownerId); if (!owner) return []; const consumed = model.relationships.filter(edge => edge.kind === 'guarantee-reliance' && edge.target === ownerId).flatMap(edge => edge.guaranteeIds); const selectedGuarantees = [...owner.guarantees].sort((a, b) => Number(consumed.includes(b.id)) - Number(consumed.includes(a.id)) || a.id.localeCompare(b.id)).slice(0, options.promisePreviewCount); const width = 320, gap = 100, rowWidth = selectedGuarantees.length * width + Math.max(0, selectedGuarantees.length - 1) * gap; const heights = selectedGuarantees.map(guarantee => { const terminal = terminalCards.find(card => card.guaranteeId === guarantee.id); const caption = terminal ? `${terminal.label} · ${owner.label}` : `PROMISE · ${owner.label}`; const hint = terminal ? 'Detail of the connected guarantee terminal' : 'Declared responsibility'; return Math.min(3, wrap(guarantee.label, width - 44, '22px system-ui').length) * 29 + wrap(caption.toUpperCase(), width - 44, '13px system-ui', .4).length * 18 + wrap(hint, width - 44, '13px system-ui').length * 18 + 76; }); const regionHeight = Math.max(176, ...heights); const x = owner.x + (owner.width - rowWidth) / 2, occupied = [...baseCards, ...terminalCards, ...annotations, ...baseLabels, ...[...promiseReservations.current.values.values()].flat()]; let y = owner.y + owner.height + 180; while (selectedGuarantees.length && (occupied.some(rect => intersects({ x, y, width: rowWidth, height: regionHeight }, rect, 100)) || routeSamples.some(point => intersects({ x, y, width: rowWidth, height: regionHeight }, point, 40)))) y += 100; const result = selectedGuarantees.map((guarantee, index) => { const terminal = terminalCards.find(card => card.guaranteeId === guarantee.id); return { ...guarantee, nodeKind: 'promise', owner: ownerId, ownerLabel: owner.label, x: x + index * (width + gap), y, width, height: Math.max(176, heights[index]), reliedOn: consumed.includes(guarantee.id), terminal }; }); promiseReservations.current.values.set(ownerId, result); return result; }), [expanded, baseCards, terminalCards, annotations, baseLabels, routeSamples, model.relationships, options.promisePreviewCount]);
  const cards = [...baseCards, ...(projectEntry ? [projectEntry] : []), ...terminalCards, ...promiseCards];
  const visible = useMemo(() => focus ? model.relationships.filter(edge => edge.id === focus || edge.source === focus || edge.target === focus || edge.guaranteeIds.includes(focus)) : model.relationships.filter(edge => mode === 'opening' ? openingIds.has(edge.id) : mode === 'all' ? edge.kind === 'architecture' : edge.kind === 'guarantee-reliance'), [model.relationships, mode, focus, openingIds]);
  const localRelationships = useMemo(() => promiseCards.map(card => card.terminal ? { id: `detail:${card.id}`, source: card.terminal.id, target: card.id, kind: 'continuation', label: `Detail of ${card.terminal.label}`, guaranteeIds: [card.id] } : { id: `ownership:${card.id}`, source: card.owner, target: card.id, kind: 'ownership', label: `Promise owned by ${card.ownerLabel}`, guaranteeIds: [] }), [promiseCards]);
  const routing = useMemo(() => { if (baseRouting.error) return baseRouting; const visibleIds = new Set(visible.map(edge => edge.id)); const unchanged = baseRouting.routes.filter(edge => visibleIds.has(edge.id)); try { const added = localRelationships.length ? validateRoutes(implementations.route({ cards: [...cards, ...endpoints], relationships: localRelationships, annotations, fixedLabels: baseLabels, options, defaults: registry.defaults }), localRelationships) : []; return { routes: [...unchanged, ...added], error: null }; } catch (error) { return { routes: unchanged, error: `Local disclosure route: ${error instanceof Error ? error.message : String(error)}` }; } }, [baseRouting, visible, localRelationships, implementations, cards, endpoints, annotations, baseLabels, options, registry]);
  const Card = implementations.card;
  const color = card => palette[Math.max(0, layout.coreIds.indexOf(card.id)) % palette.length] ?? palette[0];
  const nodes = [...cards, ...annotations, ...endpoints].map(card => ({ id: card.id, type: card.nodeKind === 'terminal' ? 'terminal' : card.nodeKind === 'promise' ? 'promise' : card.nodeKind === 'entrance' ? 'entrance' : card.nodeKind === 'endpoint' ? 'endpoint' : card.nodeKind === 'project' ? 'project' : 'stack', position: { x: card.x, y: card.y }, width: card.width, height: card.height, draggable: false, selectable: false, style: { pointerEvents: 'all' }, data: { card, Card, options, DefaultCard: DefaultStructureCard, onSelect: choose, onToggle: id => setExpanded(previous => { const next = new Set(previous); next.has(id) ? next.delete(id) : next.add(id); return next; }), onFocusRelationship: setFocus, selected: selected === card.id || selected === card.guaranteeId, detail, color: color(card) } }));
  const edges = routing.routes.map(edge => ({ id: edge.id, source: edge.source, target: edge.target, type: 'routed', sourceHandle: 's-right', targetHandle: 't-left', data: { edge, selected: selected === edge.id, onSelect: choose } }));
  useEffect(() => { const next = { selected, expanded: [...expanded], mode, focus, detail, viewport: flow.current?.getViewport() }; states.set(key, next); globalThis.__SCOPE_STRUCTURE__ ??= {}; globalThis.__SCOPE_STRUCTURE__[snapshotKey(catalog)] ??= {}; globalThis.__SCOPE_STRUCTURE__[snapshotKey(catalog)][view.id] = { ...next, cards: cards.map(({ id, x, y, width, height, nodeKind, owner }) => ({ id, x, y, width, height, nodeKind, owner })), routes: routing.routes.map(edge => ({ id: edge.id, path: edge.path, source: edge.source, target: edge.target })), error: routing.error }; }, [key, catalog, view.id, selected, expanded, mode, focus, detail, cards, routing]);
  const unavailable = model.sources.filter(source => source.status === 'unavailable');
  if (!model.components.length) return <section className="structure-view structure-empty" data-structure-view><h2>{model.project.label}</h2><p>No component declarations are available. Source readings and declaration issues remain below.</p><Issues model={model}/></section>;
  return <section className="structure-view" data-structure-view><header className="structure-frame"><div><small>{model.project.label} / STRUCTURE</small><h2>{model.project.label}: how the project works.</h2><p>{model.project.purposes[0]?.attributes.text ?? 'Project purpose has not been declared.'}</p></div><button onClick={() => { setSelected(null); setFocus(null); setExpanded(new Set()); setMode(options.initialRelationshipLayer); flow.current?.fitView({ padding: .07, duration: 300 }); }}>Return to overview</button></header>
    {(unavailable.length > 0 || model.issues.length > 0) && <Issues model={model}/>}<div className="structure-toolbar"><div><button className={mode === 'opening' ? 'chosen' : ''} onClick={() => { setMode('opening'); setFocus(null); }}>Opening route</button><button className={mode === 'all' ? 'chosen' : ''} onClick={() => { setMode('all'); setFocus(null); }}>All handoffs · {model.relationships.filter(edge => edge.kind === 'architecture').length}</button><button className={mode === 'guarantees' ? 'chosen' : ''} onClick={() => { setMode('guarantees'); setFocus(null); }}>Guarantee reliances · {model.relationships.filter(edge => edge.kind === 'guarantee-reliance').length}</button></div><span data-structure-detail={detail}>{detail === 'tile' ? 'Tile' : 'Full'} detail · {visible.length} declared connections</span></div>
    <details className="structure-relationship-list" data-structure-relationships><summary>{model.relationships.length} declared architectural relationships</summary>{model.relationships.map(edge => <button key={edge.id} data-structure-relationship={edge.id} onClick={() => choose(edge.id)}>{edge.label} · {edge.source} → {edge.target}</button>)}</details>
    {routing.error && <p className="structure-source-warning" role="alert">Routing issue: {routing.error}. Relationships remain inspectable in the sidebar.</p>}
    <div className="structure-main"><div className="structure-canvas" data-structure-map><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} edgeTypes={edgeTypes} nodesDraggable={false} nodesConnectable={false} minZoom={.12} maxZoom={1.6} onInit={instance => { flow.current = instance; const viewport = cached.viewport; viewport ? instance.setViewport(viewport) : instance.fitView({ padding: .07, minZoom: .12, maxZoom: 1 }); }} onMove={(_, viewport) => { setZoom(viewport.zoom); setDetail(previous => detailAt(viewport.zoom, options, previous)); }} onMoveEnd={(_, viewport) => { states.set(key, { ...(states.get(key) ?? {}), viewport }); }} proOptions={{ hideAttribution: true }}><Controls showInteractive={false}/><Background gap={40} size={1}/><svg><defs><marker id="structure-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path fill="#698787" d="M0,0 L8,4 L0,8 z"/></marker></defs></svg></ReactFlow></div>
      {selected && <StructureInspector catalog={catalog} id={selected} onSelect={choose} onClose={() => { setSelected(null); onClose?.(); }} controls={{ expanded, toggle: id => setExpanded(previous => { const next = new Set(previous); next.has(id) ? next.delete(id) : next.add(id); return next; }), focus: id => setFocus(id), frame: id => { const subjects = promiseCards.filter(card => card.owner === id); if (!subjects.length || !flow.current) return; const x = Math.min(...subjects.map(card => card.x)), y = Math.min(...subjects.map(card => card.y)); const bounds = { x, y, width: Math.max(...subjects.map(card => card.x + card.width)) - x, height: Math.max(...subjects.map(card => card.y + card.height)) - y }; const map = document.querySelector('[data-structure-map]'); if (map) flow.current.setViewport(getViewportForBounds(bounds, map.clientWidth, map.clientHeight, .64, .85, .08), { duration: 300 }); } }}/>}</div></section>;
}

function Issues({ model }) { const unavailable = new Set(model.sources.filter(source => source.status === 'unavailable').map(source => source.id)); const rows = [...new Map(model.issues.filter(issue => !unavailable.has(issue.source)).map(issue => [`${issue.source}:${issue.message}`, issue])).values()]; return rows.length ? <details className="structure-issues"><summary>{rows.length} relationship issue{rows.length === 1 ? '' : 's'} retained for inspection</summary>{rows.map(issue => <p key={`${issue.source}:${issue.message}`}>{issue.source}: {issue.message}</p>)}</details> : null; }

export function StructureRenderer(props) {
  const options = props.view.structure ?? DEFAULT_STRUCTURE_OPTIONS;
  const registry = useMemo(() => createStructureRegistry({ rank: defaultRank, layout: defaultBrowserLayout, route: defaultRoute, card: DefaultStructureCard, view: DefaultStructureView }, props.extensions ?? globalThis.__SCOPE_EXTENSIONS__ ?? []), [props.extensions]);
  const implementations = useMemo(() => Object.fromEntries(['rank','layout','route','card','view'].map(kind => [kind, registry.resolve(kind, options.implementations[kind] ?? 'default')])), [registry, options.implementations]);
  const View = implementations.view;
  return <View {...props} options={options} registry={registry} implementations={implementations} DefaultView={DefaultStructureView}/>;
}

export { StructureInspector as StructureSidebar };
