import React, { useMemo } from 'react';
import { buildStructureModel } from './structure-model.ts';

export function StructureSidebar({ catalog, id, onSelect, onClose, controls }) {
  const model = useMemo(() => buildStructureModel(catalog), [catalog]);
  const component = model.components.find(item => item.id === id);
  const relationship = model.relationships.find(item => item.id === id);
  const guarantee = model.components.flatMap(item => item.guarantees).find(item => item.id === id);
  const asset = catalog.assets.find(item => item.id === id);
  const connected = model.relationships.filter(item => item.source === id || item.target === id || item.guaranteeIds.includes(id));
  const name = address => model.components.find(item => item.id === address)?.label ?? address;
  const declarationAsset = relationship ? catalog.assets.find(item => item.id === relationship.declarationId) : undefined;
  const declarationOwner = typeof declarationAsset?.attributes.owner === 'string' ? declarationAsset.attributes.owner : undefined;
  const declarationSpec = declarationOwner && catalog.assets.find(item => item.kind === 'spec' && item.attributes.owner === declarationOwner);
  return <aside className="structure-sidebar" data-structure-sidebar aria-label="Architecture details"><header><strong>Architecture detail</strong><button onClick={onClose} aria-label="Close architecture detail">×</button></header>
    {controls && (component || guarantee || relationship) && <div className="structure-inspector-controls"><button onClick={() => controls.focus(id)}>Focus connections</button>{component && component.guarantees.length > 0 && <><button onClick={() => controls.toggle(component.id)}>{controls.expanded.has(component.id) ? 'Fold local promises' : 'Unfurl promises'}</button>{controls.expanded.has(component.id) && <button onClick={() => controls.frame(component.id)}>Frame local promises</button>}</>}</div>}
    {component && <><span className="kind">Component stack</span><h2>{component.label}</h2>{component.parent && <p>Within <button onClick={() => onSelect(component.parent)}>{model.components.find(item => item.id === component.parent)?.label ?? component.parent}</button></p>}<p>{component.intent || 'No declared purpose is available.'}</p><h3>Declared prominence</h3><p>{component.density.invariants} promises · {component.density.boundaries} boundaries · {component.density.relationships} relationships. These are declared signals, not a health grade.</p>
      {component.rationale && <details><summary>Why this component exists</summary><p>{component.rationale}</p></details>}{component.guarantees.length > 0 && <><h3>Promises</h3>{component.guarantees.map(item => <button className="structure-detail-link" key={item.id} onClick={() => onSelect(item.id)}>{item.label}</button>)}</>}
      {component.taxonomy.subjects > 0 && <><h3>Exact-owned taxonomy observations</h3><p>{Object.entries(component.taxonomy.states).map(([state, count]) => `${count} ${state}`).join(' · ') || 'No current state count.'}{component.taxonomy.unavailable ? ' · unavailable evidence' : ''}</p>{component.taxonomy.labels.length > 0 && <p>{component.taxonomy.stale ? 'Historical or stale labels: ' : 'Current labels: '}{component.taxonomy.labels.join(' · ')}</p>}</>}{[...component.entrances, ...component.boundaries, ...component.resources].length > 0 && <><h3>Owned architectural assets</h3>{[...component.entrances, ...component.boundaries, ...component.resources].map(item => <button className="structure-detail-link" key={item.id} onClick={() => onSelect(item.id)}>{item.label}</button>)}</>}</>}
    {(component || guarantee) && <section className="structure-connected"><h3>Connected responsibilities</h3>{connected.length ? connected.map(item => <button key={item.id} onClick={() => onSelect(item.id)}><strong>{name(item.source)} → {name(item.target)}</strong><span>{item.label}</span></button>) : <p>No explicit relationships declared for this subject.</p>}</section>}
    {relationship && <><span className="kind">{relationship.kind}</span><h2>{relationship.label}</h2><p><button onClick={() => onSelect(relationship.source)}>{relationship.source}</button> → <button onClick={() => onSelect(relationship.target)}>{relationship.target}</button></p><h3>Declared meaning</h3><p>{relationship.because || 'No rationale was declared for this relationship.'}</p><p>Declared at <code>{String(declarationAsset?.attributes.declaration ?? declarationSpec?.attributes.path ?? relationship.declarationId)}</code>{declarationAsset && <> · <button onClick={() => onSelect(declarationAsset.id)}>inspect declaration</button></>}</p>{relationship.guaranteeIds.length > 0 && <><h3>Promises involved</h3>{relationship.guaranteeIds.map(item => <button className="structure-detail-link" key={item} onClick={() => onSelect(item)}>{model.components.flatMap(component => component.guarantees).find(guarantee => guarantee.id === item)?.label ?? item}</button>)}</>}{relationship.problems.length > 0 && <><h3>Uncertainty</h3>{relationship.problems.map(problem => <p key={problem}>{problem}</p>)}</>}</>}
    {guarantee && <><span className="kind">Promise</span><h2>{guarantee.label}</h2><p>Owned by <button onClick={() => onSelect(guarantee.owner)}>{guarantee.owner}</button></p><h3>Recorded result</h3><p>{guarantee.verdict || 'No recorded verdict.'}</p>{guarantee.evidence.length > 0 && <><h3>Evidence readings</h3>{guarantee.evidence.map(evidence => <p key={evidence.id}><button onClick={() => onSelect(evidence.id)}>{String(evidence.attributes.verdict ?? evidence.attributes.grade ?? 'recorded')}</button> · {String(evidence.attributes.chokepoint ?? evidence.attributes.oracle ?? evidence.label)}</p>)}</>}{guarantee.rationale && <><h3>Rationale</h3><p>{guarantee.rationale}</p></>}{guarantee.refutations.length > 0 && <><h3>Recorded refutations</h3>{guarantee.refutations.map(item => <p key={item}>{item}</p>)}</>}{guarantee.anchors.length + guarantee.oracles.length > 0 && <><h3>Enforcement references</h3><p>{[...guarantee.anchors, ...guarantee.oracles].join(' · ')}</p></>}</>}
    {!component && !relationship && !guarantee && asset?.kind === 'description' && <><span className="kind">Project purpose</span><h2>{asset.label}</h2><p>{typeof asset.attributes.text === 'string' ? asset.attributes.text : 'Authored project explanation.'}</p><p>Declaration: <code>{String(asset.attributes.declaration ?? asset.source)}</code></p></>}
    {!component && !relationship && !guarantee && asset?.kind === 'entrance' && <><span className="kind">Entrance</span><h2>{asset.label}</h2><p>{typeof asset.attributes.description === 'string' ? asset.attributes.description : 'Declared architectural entrance.'}</p>{typeof asset.attributes.component === 'string' && <p>Owned by <button onClick={() => onSelect(String(asset.attributes.component).replace(/^(?!component:)/, 'component:'))}>{String(asset.attributes.component)}</button></p>}<p>Declaration: <code>{String(asset.attributes.declaration ?? asset.source)}</code></p></>}
    {!component && !relationship && !guarantee && asset?.kind === 'guarantee' && <><span className="kind">Evidence reading</span><h2>{asset.label}</h2><p>Verdict: {String(asset.attributes.verdict ?? 'not recorded')}</p><p>Oracle: {String(asset.attributes.oracle ?? 'not recorded')}</p><p>Chokepoint: {String(asset.attributes.chokepoint ?? 'not recorded')}</p><p>Grade: {String(asset.attributes.grade ?? 'not recorded')}</p><p>Source: <code>{asset.source}</code></p></>}
    {!component && !relationship && !guarantee && (asset?.kind === 'transition' || asset?.kind === 'resource') && <><span className="kind">{asset.kind}</span><h2>{asset.label}</h2><p>{String(asset.attributes.translates ?? asset.attributes.intent ?? asset.attributes.description ?? 'Declared architectural asset.')}</p><p>Source: <code>{asset.source}</code></p></>}
    {!component && !relationship && !guarantee && asset && !['description', 'entrance', 'guarantee', 'transition', 'resource'].includes(asset.kind) && <><span className="kind">Reference</span><h2>{asset.label ?? id}</h2><p>This selected address is outside the current Structure projection. It remains a catalog reference and is not represented as an invented architectural relationship.</p></>}
  </aside>;
}
